// Supabase Auth "Send Email" Hook.
//
// Configure in Dashboard: Authentication -> Hooks -> Send Email Hook,
// pointing at this function's URL, with a signing secret set as the
// SEND_EMAIL_HOOK_SECRET env var (format: whsec_xxxxx, generated by the
// Dashboard when you enable the hook). Once enabled, Supabase stops sending
// its own confirmation/recovery emails and calls this function instead for
// EVERY auth email type (signup, recovery, magic link, email change,
// invite, reauthentication). We only build custom templates for signup and
// recovery per the confirmed scope — everything else is a safe no-op that
// still returns 200 so auth flows relying on it (e.g. magic link login, if
// ever enabled) are not silently broken, they just won't have custom
// branding yet.
//
// Deploy: supabase functions deploy auth-email-hook --no-verify-jwt
// Secrets: supabase secrets set RESEND_API_KEY=... SEND_EMAIL_HOOK_SECRET=whsec_... APP_BASE_URL=https://emaxinvest.site

import { passwordResetEmail, signupConfirmationEmail } from "../_shared/templates.ts";
import { sendEmail } from "../_shared/email.ts";

const HOOK_SECRET = Deno.env.get("SEND_EMAIL_HOOK_SECRET") || "";

async function verifySignature(payload: string, headers: Headers): Promise<boolean> {
  if (!HOOK_SECRET) {
    console.error("SEND_EMAIL_HOOK_SECRET not set — refusing to process unverified webhook");
    return false;
  }

  const id = headers.get("webhook-id");
  const timestamp = headers.get("webhook-timestamp");
  const signatureHeader = headers.get("webhook-signature");
  if (!id || !timestamp || !signatureHeader) return false;

  // Reject old requests (>5 min) to mitigate replay attacks.
  const ts = Number(timestamp);
  if (!Number.isFinite(ts) || Math.abs(Date.now() / 1000 - ts) > 300) return false;

  const secretBytes = base64Decode(HOOK_SECRET.replace(/^whsec_/, ""));
  const signedContent = `${id}.${timestamp}.${payload}`;

  const key = await crypto.subtle.importKey(
    "raw",
    secretBytes,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const sigBuffer = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(signedContent));
  const expected = base64Encode(new Uint8Array(sigBuffer));

  // webhook-signature header looks like "v1,<base64sig> v1,<base64sig2>..."
  const candidates = signatureHeader.split(" ").map((s) => s.split(",")[1]).filter(Boolean);
  return candidates.includes(expected);
}

function base64Decode(str: string): Uint8Array {
  const bin = atob(str);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

function base64Encode(bytes: Uint8Array): string {
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}

Deno.serve(async (req: Request) => {
  const payload = await req.text();

  const verified = await verifySignature(payload, req.headers);
  if (!verified) {
    return new Response(JSON.stringify({ error: "invalid signature" }), { status: 401 });
  }

  let body: any;
  try {
    body = JSON.parse(payload);
  } catch {
    return new Response(JSON.stringify({ error: "invalid json" }), { status: 400 });
  }

  const user = body.user;
  const emailData = body.email_data;
  const actionType: string = emailData?.email_action_type || "";
  const email: string = user?.email || "";

  if (!email) {
    return new Response(JSON.stringify({ error: "no email on user" }), { status: 400 });
  }

  // Supabase builds the confirmation/recovery link from these fields. See:
  // https://supabase.com/docs/guides/auth/auth-hooks/send-email-hook
  const site = Deno.env.get("SUPABASE_URL") || "";
  const verifyBase = `${site}/auth/v1/verify`;
  const link = `${verifyBase}?token=${encodeURIComponent(emailData?.token_hash || "")}&type=${encodeURIComponent(
    emailData?.email_action_type || ""
  )}&redirect_to=${encodeURIComponent(emailData?.redirect_to || "")}`;

  try {
    if (actionType === "signup") {
      const { subject, html } = signupConfirmationEmail({ email, confirmUrl: link });
      const result = await sendEmail({ to: email, subject, html });
      if (!result.ok) throw new Error(result.error);
    } else if (actionType === "recovery") {
      const { subject, html } = passwordResetEmail({ email, resetUrl: link });
      const result = await sendEmail({ to: email, subject, html });
      if (!result.ok) throw new Error(result.error);
    } else {
      // email_change, magic_link, invite, reauthentication — not in scope
      // yet. Log and let Supabase's flow continue without blocking the user.
      console.log(`auth-email-hook: no custom template for action_type="${actionType}", skipping`);
    }
  } catch (err) {
    console.error("auth-email-hook send failed", err);
    // Returning a non-2xx here causes Supabase to surface an error to the
    // user's signup/reset attempt, so we deliberately still return 200 —
    // a failed branded email should not block account creation or recovery.
  }

  return new Response(JSON.stringify({}), { status: 200, headers: { "Content-Type": "application/json" } });
});
